intel/PerfSpect

builder/Dockerfile
Need validation in cloud environments
=> Updated Dockerfile to move Ubuntu version 18.04 and python version 3.7

tools/Makefile
addresses #105 
pin systat version to known buildable and working version
=> pin systat version

cmd/metrics/resources/base.html
make consistent with other HTML reports, i.e., Intel(r) PerfSpect.
=> fix metrics HTML title field

internal/report/table_helpers.go
Handle GiB units when parsing L3 size.
=> recognize L3 cache size in GiB

THIRD_PARTY_PROGRAMS, cmd/report/report.go, internal/common/common.go, internal/report/benchmarking_table_helpers.go, internal/report/table_defs.go, internal/script/script_defs.go, tools/Makefile
add fio to benchmark storage device
=> add storage performance benchmark to 'report' command

cmd/metrics/metadata.go, cmd/metrics/metrics.go, cmd/metrics/resources/base.html, cmd/metrics/summary.go
=> add metadata tab to metrics summary HTML report

internal/report/table_helpers.go
log error, don't put it in the report output
=> remove parse error from report, add to log

internal/script/script.go
When sudo password is collected via prompt from perfspect, it needs to be provided to scripts that require elevated privileges.
=> provide sudo password to script when needed

internal/report/html.go
No change in functionality, refactoring only.
=> refactor html report generation to reduce duplication

cmd/metrics/resources/events/x86_64/GenuineIntel/emr.txt, cmd/metrics/resources/events/x86_64/GenuineIntel/emr_nofixedtma.txt, cmd/metrics/resources/events/x86_64/GenuineIntel/gnr.txt, cmd/metrics/resources/events/x86_64/GenuineIntel/icx.txt, cmd/metrics/resources/events/x86_64/GenuineIntel/icx_nofixedtma.txt, cmd/metrics/resources/events/x86_64/GenuineIntel/spr.txt, cmd/metrics/resources/events/x86_64/GenuineIntel/spr_nofixedtma.txt, cmd/metrics/resources/events/x86_64/GenuineIntel/srf.txt, cmd/metrics/resources/metrics/x86_64/GenuineIntel/emr.json, cmd/metrics/resources/metrics/x86_64/GenuineIntel/emr_nofixedtma.json, cmd/metrics/resources/metrics/x86_64/GenuineIntel/gnr.json, cmd/metrics/resources/metrics/x86_64/GenuineIntel/icx.json, cmd/metrics/resources/metrics/x86_64/GenuineIntel/icx_nofixedtma.json, cmd/metrics/resources/metrics/x86_64/GenuineIntel/spr.json, cmd/metrics/resources/metrics/x86_64/GenuineIntel/spr_nofixedtma.json, cmd/metrics/resources/metrics/x86_64/GenuineIntel/srf.json
added on GNR, SRF, EMR, SPR, and ICX.
=> add branch mispredict ratio metric

internal/report/table_helpers.go
Add AOP and LLCPP prefetchers to report.
=> report state of new GNR prefetchers

cmd/root.go
--syslog will direct logs to local system's syslog daemon
=> Add syslog logging support and refactor file logging

internal/script/script_defs.go
Previous script depended on SNC being enabled so that NUMA nodes aligned with dies. This change does not make that assumption. It counts dies using lspci.
=> Refactor core ID handling for AVX-Turbo benchmark to support interleaving across dies on GNR

cmd/telemetry/telemetry.go, internal/report/html.go, internal/report/table_defs.go, internal/report/table_helpers.go, internal/script/script_defs.go
Adds summary CPU frequency. Also combines --cpu, --cpuavg, --irq, and the new frequency feature all under the --cpu flag.
=> Enhance turbostat output handling and add CPU frequency

cmd/report/report.go, internal/report/table_defs.go, internal/script/script_defs.go
=> Add network configuration (from sysctl) table to report

cmd/config/config.go, cmd/metrics/event_frame.go, cmd/metrics/metadata.go, cmd/metrics/metric.go, cmd/metrics/metric_defs.go, cmd/metrics/metrics.go, cmd/metrics/perf_mux.go, cmd/metrics/process.go, internal/common/common.go, internal/cpudb/cpudb.go, internal/report/benchmarking_table_helpers.go, internal/report/html.go, internal/report/report.go, internal/report/stacks_helpers.go, internal/report/table_defs.go, internal/report/table_helpers.go, internal/script/script.go, internal/target/target.go, internal/util/util.go
Ran:
go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -fix -test ./...
to automatically update code to use new go features
=> apply go modernize updates

cmd/metrics/resources/base.html, cmd/metrics/summary.go
and refactor metrics visualization to use text template placeholders for data
=> Add TMA Level 1 metrics in chart over time

cmd/config/config.go, cmd/flame/flame.go, cmd/metrics/event_defs.go, cmd/metrics/event_frame.go, cmd/metrics/metrics.go, cmd/metrics/summary.go, cmd/report/report.go, cmd/root.go, cmd/telemetry/telemetry.go, internal/common/common.go, internal/report/html.go, internal/report/table_defs.go, internal/script/script.go, internal/target/target.go, internal/util/util.go
Remove a couple util functions that can be handled directly by the slices package.
Also renamed a couple util functions for readability.
=> Refactor utility function calls to use slices package

internal/report/dimm_table_helpers.go, internal/report/html.go
=> Format DIMM description in report to include DIMM speed and configured speed

cmd/config/config.go, cmd/flame/flame.go, cmd/lock/lock.go, cmd/metrics/metrics.go, cmd/report/report.go, cmd/telemetry/telemetry.go, internal/common/targets.go, internal/script/script_defs.go, internal/util/util.go
There are a few command line input parameters that either aren't validated or need improved validation.
=> Add missing input validation

cmd/flame/flame.go, cmd/lock/lock.go, cmd/report/report.go, cmd/telemetry/telemetry.go, internal/common/common.go, internal/script/script_defs.go
Make it easier to add new script parameters, as needed.
=> Refactor script parameters to use map instead of struct

cmd/lock/lock.go
As @harp-intel suggested, currently the xlsx and json output format for the 'lock' command did not make any sense, so try to remove those options and only support html and txt.
=> make lock command only support html and txt output format

internal/script/script_defs.go
Originally the 'lock' command write the profiling data into current working directory, while instead it should be located into the temp directory.
=> make perf lock collected data into temp files

cmd/metrics/resources/events/x86_64/AuthenticAMD/turin.txt, cmd/metrics/resources/metrics/x86_64/AuthenticAMD/turin.json
Co-authored-by: Prashant Yadav prashant.yadav@amd.com
=> added amd turin support

cmd/config/config.go, cmd/config/flag.go, cmd/config/flag_groups.go, cmd/config/set.go, cmd/flame/flame.go, cmd/lock/lock.go, cmd/metrics/event_frame.go, cmd/metrics/metadata.go, cmd/metrics/metric_defs.go, cmd/metrics/metrics.go, cmd/metrics/perf.go, cmd/metrics/perf_mux.go, cmd/metrics/print.go, cmd/metrics/process.go, cmd/metrics/summary.go, cmd/report/report.go, cmd/telemetry/telemetry.go, internal/common/common.go, internal/common/targets.go, internal/script/script.go, internal/target/local_target.go, internal/target/remote_target.go, internal/target/target.go, internal/util/util.go
Refactor and simplify (where possible) the logic.
=> Address issues found with collecting metrics for cgroups

cmd/report/report.go, cmd/telemetry/telemetry.go
make equivalent to report command's flagAll handling
=> update telemetry command to enable flagAll by default 

internal/report/table_helpers.go
- simplify time format
- add system type
- use AMD specific labels for HT (SMT) and Turbo (Boost)
=> adjustments to system summary field

cmd/metrics/perf.go
need to make sure that remote target uses the bundled perf to collect events
=> always push perf to remote target

cmd/metrics/event_frame.go, cmd/metrics/loader_component.go, cmd/metrics/metadata.go, internal/util/util.go
reduce number of event groups by merging small groups together
=> merge arm event groups

cmd/metrics/loader.go, cmd/metrics/loader_component.go, cmd/metrics/loader_util.go, cmd/metrics/summary.go, go.mod, go.sum
Kinetic/govaluate no longer maintained.
=> use casbin/govaluate
