- .github/workflows/build.yml
> Use Ubuntu 18 build container

- Makefile
Earlier commit did not include these files in the pyinstaller build, thus they are not available at runtime.
> add nofixedtma metric files as build time resources

- .github/workflows/build-test.yml
- .github/workflows/codeql.yml
- Dockerfile
- build.Dockerfile
Pin dependencies as recommended by OpenSSF scorecard.
https://securityscorecards.dev/viewer/?uri=github.com/intel/PerfSpect
> pin build process dependencies

- .gitignore
- Makefile
- cmd/config/config.go
- cmd/metrics/metrics.go
- cmd/metrics/print.go
- cmd/report/report.go
- cmd/root.go
- cmd/telemetry/telemetry.go
- internal/common/common.go
- internal/report/report.go
- internal/script/script.go
- internal/script/script_test.go
- internal/target/target.go
- mostly checking function error return value
> address issues raised by golangci-lint

- cmd/metrics/metrics.go
- internal/util/util.go
Addresses https://github.com/intel/PerfSpect/issues/96.
When SIGINT or SIGTERM is received by the perfspect process, the signal will be sent to child processes.
This is to address the problem seen when SIGINT is sent through the signal command, e.g., when scripted.
> send SIGINT and SIGTERM to children when received

- internal/common/common.go
The 'flame' and 'telemetry' commands require a specified duration. By default, it is 30 seconds. This code change shows the duration in the console status, e.g., 
```
$ ./perfspect telemetry
myhost.foo.xyz.com  ⣽  collecting data, duration=30s
```
> show flame and telemetry duration in status

- Makefile
- cmd/root.go
Resolves https://github.com/intel/PerfSpect/issues/99.
> build tarball without version in name

- internal/script/script.go
- internal/target/target.go
Closes #109 
If target user is a superuser, don't prepend sudo to the command that runs the collection script on the target.
> don't prepend sudo to command if user is superuser

- internal/script/script.go
- internal/script/script_defs.go
- internal/script/script_test.go
Use the Linux timeout command in scripts that we have historically seen enter endless loops or run for an unexpected duration.
This addresses a portion of #113.
> timeout on commands

- cmd/report/report.go
When MLC isn't available, we don't measure memory latency. The Benchmark Summary table displays "ns" regardless.
This change will cause the field to be blank when no data is available.
> clean up benchmark summary table when no min latency collected

- cmd/report/report.go
With no category flags specified, 'all' is true by default.  If any categories are selected, all will be dynamically changed to false.
This change eliminates some confusion in the help text.
> perfspect report flag 'all' is true by default

- internal/cpudb/cpu_defs.go
Add Turin to list of CPUs so it can be identified when encountered.
> add AMD Turin CPU identifier

- cmd/metrics/event_defs.go
- cmd/metrics/event_frame.go
- cmd/metrics/metadata.go
- cmd/metrics/metric_defs.go
- cmd/metrics/metrics.go
- cmd/metrics/summary.go
GCP c4-standard instances expose PMUs at different levels -- disabled, architectural, standard, enhanced. Only c4-standard-96 and 192 support enhanced.  See GCP docs for details on what each level includes.
This PR handles the issues we ran into when attempting to collect metrics on the above, e.g., unexpected "not supported" events and zero values causing expressions to evaluate as +Inf.
> support for GCP C4 instances

- cmd/metrics/metadata.go
- cmd/metrics/metric.go
If an error is encountered when checking for various event types, continue with a warning and assume that the event type is not supported.
> assume events not supported on failure when loading metadata for metrics command

- cmd/metrics/metrics.go
If another tool is using the PMUs, PerfSpect metrics will not get accurate data.
> make sure PMUs are not in use when running the metrics command

- cmd/metrics/metadata.go
- cmd/metrics/nmi_watchdog.go
- cmd/metrics/process.go
- internal/script/script.go
- internal/target/target.go
Changed the target RunCommand interface to accept a boolean that indicates if the SSH connection can be re-used, i.e., use SSH control master.
Changed long running commands, e.g., the report collection master script, to NOT use the SSH control master. This allows SIGINT to stop child processes, e.g., ssh.
Now, if collecting remote data using the 'report' command, ctrl-c will interrupt, and stop, PerfSpect.
> Enable interruption of PerfSpect with SIGINT (ctrl-c) when collecting data over SSH

- cmd/metrics/summary.go
Ignore infinite event values, in addition to NaN values, when creating summary reports.
> filter out infinite values in metrics summary

- cmd/metrics/metric_defs.go
Fixes bug in the "metrics" command.
The "--list" option prints metrics names after stripping the common "metric_" prefix.
The "--metrics" option expects the "metric_" prefix to exist.
After this change, the "--metrics" option will accept metrics names without the "metric_" prefix.
> accept metric list without including "metric_" prefix

- internal/report/html.go
- internal/report/html_flamegraph.go
- internal/report/report.go
- internal/report/table_defs.go
Add custom 'no data found' messages for memory bandwidth and latency benchmarks.
> add support for customized "no data found" message for any table

- cmd/metrics/resources/base.html
- cmd/metrics/summary.go
> add 2nd level TMA metrics to chart

- cmd/flame/flame.go
- cmd/lock/lock.go
fix bug in help output for flame and lock commands
> change flame and lock help to show 'all' is default format option

- cmd/metrics/print.go
`perfspect metrics --granularity cpu` will now print metrics for all CPUs
`perfspect metrics --granularity socket` will now print metrics for all sockets
> fix bug where higher granularity metrics are not properly printed

- internal/script/script_defs.go
replace bc in scripts, now runs on Ubuntu 22.04 AWS images:
```
$ ./perfspect report --target 10.114.163.29 --user ubuntu --key ~/config/tools-cicd-us-west-2.pem --benchmark numa,memory --debug --host --format txt --os
10.114.163.29         ⣯  collection complete                     
10.114.163.29:
Host
====
Host Name: ip-10-114-163-29
Time:      Wed Jan 29 23:22:48 UTC 2025
System:    Amazon EC2 m7a.8xlarge
Baseboard: Amazon EC2 Not Specified
Chassis:   Amazon EC2 Other
Operating System
================
OS:              Ubuntu 22.04.5 LTS
Kernel:          6.8.0-1021-aws
Boot Parameters: BOOT_IMAGE=/boot/vmlinuz-6.8.0-1021-aws root=PARTUUID=7e653fbc-1bf4-4ca7-905a-3ed95c2fd3f9 ro console=tty1 console=ttyS0 nvme_core.io_timeout=4294967295 panic=-1
Microcode:       0xa101154
NUMA Bandwidth …
```
> don't use bc in script as it is not available, by default, on some Linux OS distributions

- cmd/metrics/event_frame.go
- cmd/metrics/metric_defs.go
Discovered two issues --
1) the constant TSC needed to be divided by # of sockets in 'socket' mode and # of cpus in 'cpu' mode.
2) the coalescing of events in 'socket' mode was not including all events in the accumulated value
> fix metrics socket and cpu granularity metric calculations

- cmd/flame/flame.go
- cmd/lock/lock.go
- cmd/report/report.go
- cmd/telemetry/telemetry.go
- internal/common/common.go
- internal/report/html.go
- internal/report/table_defs.go
- internal/script/script_defs.go
- tools/Makefile
- tools/build.Dockerfile
Use Intel [ProcessWatch ](https://github.com/intel/processwatch) to report instruction mix within the PerfSpect telemetry command.
> add instruction mix reporting to telemetry command

- cmd/metrics/event_defs.go
This is a regression introduced in v3.2. OCR events are not available when uncore events are not available.
> fix regression in metrics command causing error on some AWS m5 and m6 instance types

- cmd/metrics/metric.go
- cmd/metrics/metrics.go
> address race condition in metrics event processing

- cmd/metrics/metrics.go
a follow-on to commit that fixed race condition
> process last set of events consistently

- cmd/telemetry/telemetry.go
- internal/common/common.go
- internal/script/script.go
- internal/script/script_defs.go
Add support for telemetry --duration=0. This will collect telemetry until the user interrupts it with e.g., ctrl-c.
Indefinite telemetry collection will only work when data is being collected on local host.
> enable indefinite duration for telemetry collection

- cmd/metrics/resources/base.html
- cmd/metrics/summary.go
- internal/report/html.go
Example in metrics summary HTML:
> show timestamps in metrics summary and telemetry charts

- cmd/metrics/metrics.go
no need to copy perf to target, if it is already installed. Saves startup time by not copying perf which is a large binary.
> use remote target's perf for metrics collection if it is installed and new enough

- cmd/config/config.go
- internal/report/table_defs.go
- internal/report/table_helpers.go
- internal/script/script_defs.go
On newer architectures (SRF, GNR, ...) the max/min die frequencies can be set independently. This PR updates the report command to read them independently and the config command to set them independently.
> Get and set compute and I/O die max/min frequencies independently

- cmd/config/config.go
- internal/report/table_defs.go
- internal/report/table_helpers.go
- internal/script/script_defs.go
...also adds insight that indicates when ELC is latency-optimized but EPB is non-zero
> use alternate EPB value when configured to do so

- internal/common/common.go
- internal/report/html.go
- internal/report/report.go
- internal/report/table_defs.go
Some report tables are only relevant to certain CPUs. This change allows us to associate tables with a limited set of CPUs, similar to how the report scripts work.
> report tables associated with CPU models

- internal/cpudb/cpu_test.go
- internal/cpudb/cpudb.go
- internal/report/table_helpers.go
Perfspect was incorrectly identifying GNR_X* when sockets are disabled via BIOS.
> fix GNR_X* microarchitecture detection

- internal/script/script_defs.go
invert loops in pmu busy checker to increase time between reads without increasing overall time
> improve PMU busy checker script for easier debugging

- cmd/report/report.go
- internal/cpudb/cpu_defs.go
- internal/cpudb/cpudb.go
- internal/script/script_defs.go
Report now differentiates between SRF-SP and SRF-AP.
> Add support for Sierra Forest AP microarchitecture in CPU database

- cmd/metrics/event_defs.go
- cmd/metrics/event_frame.go
- cmd/metrics/summary.go
- go.mod
- go.sum
- internal/report/html.go
- internal/report/html_flamegraph.go
These experimental packages are now available in the Go standard library.
1. `golang.org/x/exp/slices` -> `slices` (https://go.dev/doc/go1.21#slices)
2. `golang.org/x/exp/rand` -> `math/rand/v2` (https://go.dev/doc/go1.22#math_rand_v2)
`golang.org/x/exp/rand` has been deprecated and scheduled to be deleted.
Reference: https://github.com/golang/exp/commit/f9890c6ad9f380fd3cdb66a33843f522d4790e03
> Replace `golang.org/x/exp` with stdlib

- cmd/config/config.go
- cmd/metrics/metrics.go
- cmd/root.go
- internal/common/common.go
- internal/common/targets.go
- internal/progress/multispinner.go
- internal/script/script.go
- internal/target/target.go
- --tempdir flag overrides default (usually /tmp) in case /tmp is on a filesystem mounted with the 'noexec' option
- improve error messages, e.g., when temp dir lands on a 'noexec' file system
- eliminate --targettemp flag
There are two temporary directories created.
- for the application, this is where dependencies and scripts are written before being copied to the target
- for the target (remote or local), this is where the scripts and dependencies are stored and executed (must not be 'noexec')
Only the 2nd temporary directory location can be changed with --tempdir.  The 1st always lands in the system's default temp, e.g., /tmp.
Both directories are cleaned up (removed) when the application exits...unless the --debug flag is specified.
> Refactor temporary directory handling

- build.Dockerfile
- builder/build.Dockerfile
- cmd/config/config.go
- internal/report/prefetcher_defs.go
- internal/report/table_defs.go
- internal/script/script.go
- internal/script/script_defs.go
Intel families will expand in the future from the current "6" to other values. This change replaces most uses of "6" with the CPU vendor, e.g., "GenuineIntel".
> Enhance script and table definitions to include vendor filtering for target compatibility

- cmd/config/config.go
- cmd/flame/flame.go
- cmd/lock/lock.go
- cmd/metrics/metadata.go
- cmd/metrics/metrics.go
- cmd/metrics/resources/base.html
- cmd/metrics/summary.go
- cmd/telemetry/telemetry.go
- internal/common/common.go
- internal/report/table_defs.go
- internal/report/table_helpers.go
- internal/script/script_defs.go
> Add brief system summary to metrics, telemetry, flame, and lock reports

- internal/report/benchmarking_table_helpers.go
- internal/report/table_defs.go
- internal/report/table_helpers.go
Add Cores per Die column, for multi-die architectures
```
Maximum Frequency
=================
Cores   Cores per Die   SSE   AVX2   AVX512   AVX512H   AMX
-----   -------------   ---   ----   ------   -------   ---
1-44    1-22            3.8   3.6    3.5      3.5       3.0
45-52   23-26           3.8   3.5    3.2      3.2       2.8
53-60   27-30           3.8   3.4    3.1      3.1       2.6
61-68   31-34           3.8   3.2    2.9      2.6       2.2
69-72   35-36           3.8   3.2    2.8      2.5       2.2
73-76   37-38           3.8   3.1    2.8      2.5       2.2
77-80   39-40           3.8   3.0    2.7      2.4       2.1
81-86   41-43           3.8   3.0    2.7      2.4       2.1
```
> Enhance core frequency reporting for multi-die architectures

- cmd/metrics/event_defs.go
- cmd/metrics/event_frame.go
- cmd/metrics/metrics.go
This pull request focuses on improving logging, refining error handling, and enhancing validation logic in the metrics collection codebase. The most significant changes include switching certain log levels from `Warn` to `Debug`, restructuring error handling in event parsing, and adding more detailed flag validation checks.
* Changed log levels from `Warn` to `Debug` for cases where there are no collectable events in a group or uncollectable events on the target in `cmd/metrics/event_defs.go`. [[1]](diffhunk://#diff-a20e5c9b922d2b0cb65050aa38c02112d43eb2a57c7a304e64fef929bff09496L80-R80) [[2]](diffhunk://#diff-a20e5c9b922d2b0cb65050aa38c02112d43eb2a57c7a304e64fef929bff09496L93-R93)
* Added debug logs for unsupported or uncounted events in `cmd/metrics/event_frame.go`. These logs provide …
> Refactor logging levels and improve event parsing error handling

- internal/common/common.go
- internal/report/render_excel.go
- internal/util/util.go
- internal/util/util_test.go
This pull request introduces enhancements to the reporting functionality and utility methods, focusing on table name extraction, merging logic, and comprehensive testing. The changes improve the handling of multi-target reports by ensuring ordered and unique table names are maintained across targets.
* Updated `createReports` in `internal/common/common.go` to use `mergedTableNames` for multi-target reports, ensuring table names are merged uniquely and in order.
* Added `extractTableNamesFromValues` function to extract table names from processed table values, enabling better organization of table names for multi-target reports.
* Introduced `MergeOrderedUnique` in `internal/util/util.go`, a utility function for merging slices while maintaining order and ensuring uniqueness. This is used to …
> Tables from all targets in multi-target report

- cmd/report/report.go
- internal/report/table_defs.go
- internal/report/table_helpers.go
- internal/report/table_helpers_test.go
- internal/script/script_defs.go
This pull request introduces significant updates to the handling of network interface data, focusing on improving data parsing, enhancing script functionality, and refining table definitions. The changes eliminate reliance on the `lshw` tool, replace it with `udevadm` and `ethtool`, and introduce a new parsing function for network interface information. Additionally, test coverage has been expanded to ensure correctness of the new parsing logic.
* [`internal/report/table_helpers.go`](diffhunk://#diff-74f57111747df6d7e50f502eb3b2009992af236b07af3298ae22be7b5feb2cf5L1345-R1398): Replaced the `nicInfoFromOutput` function with `parseNicInfo`, which now parses NIC information using structured output from `ethtool` and `udevadm`. This change improves accuracy and eliminates dependency on …
> refactor NIC info collection

- cmd/metrics/metadata.go
need to overflow the GP counters to determine if the fixed counter is supported
> fix determination of availability of fixed counters

- cmd/metrics/metrics.go
Instead of reporting an error an exiting the program, we report a warning to stderr and the log then continue.
> pmu in use from error to warning

- internal/report/cpu_defs.go
- internal/report/table_defs.go
- internal/script/script_defs.go
Add Graviton 4 to recognized CPUs.
> add Graviton 4, Neoverse-V2

- internal/report/cpu_defs.go
This pull request adds support for the Arrow Lake microarchitecture to the `cpuDefinitions` array in the `internal/report/cpu_defs.go` file.
Hardware support update:
* [`internal/report/cpu_defs.go`](diffhunk://#diff-106af3936374ffda2e6b338c7f1e79b97f5c4bfcbdf3bbf1b6b623aeb6c750e4R44): Added a new CPU definition for the Arrow Lake microarchitecture, specifying its family, model, stepping, architecture, memory channel count, logical thread count, and cache way count.
> add Arrow Lake

- tools/Makefile
Add perf-archive.sh to the default tools build target, remove the dependencies for kernel
The RunScripts call will extract the perf-archive from the script resource directory to
target, and configure the PATH to make sure the copied perf-archive script takes effect.
Linux perf tool trace archive as external, will put a dash to perf archive and executed perf-archive 
script found in PATH.
> Use buildin perf archive sh

- .github/workflows/build-test.yml
- .gitignore
- Makefile
- builder/build.sh
- tools/Makefile
- tools/build.Dockerfile
Cross compile supporting toolchain (where possible)
For perf, I bumped up the version to get a newer version of perf that supports Neoverse V2 cores
processwatch has ARM support, but we can't crosscompile right now as we need an ARM kernel to do the btf dump
e.g.
```
src/bpf/insn/build.sh
${BPFTOOL} btf dump file /sys/kernel/btf/vmlinux format c > ${DIR}/vmlinux.h
```
Did a basic perf test on a Neoverse V2 guest to validate perf:
```
$ sudo ./perf stat -- sleep 1
Performance counter stats for 'sleep 1':
0.53 msec task-clock                       #    0.001 CPUs utilized
2      context-switches                 #    3.784 K/sec
0      cpu-migrations                   #    0.000 /sec
65      page-faults                      #  122.975 K/sec
1547407      instructions                     # …
```
> Cross compile tools for ARM (aarch64)

- Makefile
- builder/build.sh
- tools/Makefile
- tools/build.Dockerfile
This pull request refactors the build system to unify resource directories and streamline the handling of x86_64 and aarch64 architectures. It removes redundant logic, simplifies the `Makefile` structure, and consolidates resources into architecture-specific subdirectories under a single `bin` directory. Additionally, it updates the Docker build process to reflect these changes.
* Consolidated resource directories for x86_64 and aarch64 architectures into `internal/script/resources` and removed architecture-specific subdirectories (`x86_64` and `aarch64`) in the `Makefile`. [[1]](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L31-L51) [[2]](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R162-R164)
* Simplified the …
> x86_64 and aarch64 tools build as siblings

- internal/report/table_defs.go
This pull request refines error handling in telemetry table generation functions by adjusting the logging behavior when no package rows are found. Instead of treating these cases as errors, they are now logged as warnings to better reflect their non-critical nature.
* [`internal/report/table_defs.go`](diffhunk://#diff-40020381fb8631bc46477e98732857d1990925cdefdd181ce398cfdab4bfff2cL2431-R2432): Updated `temperatureTelemetryTableValues` to log a warning instead of an error when no package rows are found, clarifying that this is not a critical issue but expected behavior in some cases.
* [`internal/report/table_defs.go`](diffhunk://#diff-40020381fb8631bc46477e98732857d1990925cdefdd181ce398cfdab4bfff2cL2472-R2469): Updated `frequencyTelemetryTableValues` with similar changes, logging a …
> core temperature and frequency telemetry when no uncore

- cmd/telemetry/telemetry.go
- internal/script/script_defs.go
This pull request introduces a new flag, `flagInstrMixFrequency`, to enhance the telemetry functionality by allowing users to specify the number of instructions between samples when no PID is provided. It also includes updates to improve flag validation and script parameter handling.
Previous value for frequency was hard-coded to 1,000,000 when no PID is specified. We observed too much overhead in this configuration. The new --instrmix-frequency flag defaults to 10,000,000 to reduce overhead in the default configuration but allows the user to override this value if more frequent samples are required. Minimum is set to 100,000 to avoid catastrophic overhead.
* Added `flagInstrMixFrequency` to `var` and `const` declarations in `cmd/telemetry/telemetry.go`, enabling users to configure the …
> add flag for instruction mix frequency in telemetry command

- tools/Makefile
- tools/build.Dockerfile
1. use unified kernel version 6.15.3
2. enable llvm-perf support to speed up perf report
3. fix potential segment fault in new libdwfl
4. support more features like dwarf,unwind,tracefs,capsstone
> enhancements for perf-x86_64 static build

- internal/report/table_defs.go
This pull request includes a small but critical change to the logic in the `acceleratorTableInsights` function within the `internal/report/table_defs.go` file. The change ensures that insights are generated only when the `queues` value is explicitly `"None"` for DSA and IAA accelerators, rather than when it is not `"None"`.
> Fix accelerator table insights

- cmd/root.go
- go.mod
- go.sum
This pull request refines the `onIntelNetwork` function to improve its DNS lookup mechanism by introducing a timeout and enhanced error handling. The changes ensure that network checks are more robust and provide better debugging information.
* [`cmd/root.go`](diffhunk://#diff-ab967ab1a2f3a1b769106eeb7bfe892ef0e81d1d27811fa15be08e6749feee1fL306-R323): Updated the `onIntelNetwork` function to use a `context.WithTimeout` for a 1-second timeout during DNS resolution, ensuring quicker failure in case of network issues. Introduced a custom resolver (`net.Resolver`) and added detailed logging for timeout and other DNS errors using `slog.Debug`.
> add timeout for intel network check

- cmd/metrics/process.go
Tested in containerd environment run by kubectl. REquires the extra path to be scanned for cgroups under cri-containerd.
> Added support for cri-containerd for cgroup scope

- internal/script/script_defs.go
This pull request updates the way the `mlc` (Memory Latency Checker) tool is invoked within the `internal/script/script_defs.go` script definitions. The changes add specific options to the `mlc` command to control buffer size and output format for both latency and bandwidth measurements.
Updates to `mlc` command usage:
* The `mlc --loaded_latency` command now includes the `-b500m` option to set the buffer size to 500MB and the `-X` option to use one thread per core.
* The `mlc --bandwidth_matrix` command also adds the `-b500m` and `-X` options for the same purposes.
> Update memory benchmarks for larger L3 cache systems

- cmd/metrics/event_frame.go
- cmd/metrics/event_frame_test.go
- cmd/metrics/metrics.go
- internal/script/script.go
- internal/target/helpers.go
- internal/target/local_target.go
- internal/target/remote_target.go
- internal/target/target.go
eliminate race condition in perf event processing
This pull request refactors how perf event output is collected and processed in the metrics package, shifting from line-by-line string handling to batching by interval using byte slices. The changes improve the accuracy and efficiency of event grouping, simplify channel usage, and add robust parsing and testing for interval extraction. Most changes are in `cmd/metrics/metrics.go`, with supporting updates to target and script streaming interfaces.
**Perf event batching and processing improvements:**
* Refactored perf event output handling to batch events by interval using byte slices (`[][]byte`), replacing previous timer-based grouping and string channels. This ensures each batch corresponds to a specific perf interval, improving accuracy …
> refactor metrics event processing

- cmd/metrics/event_defs.go
- cmd/metrics/event_frame.go
- cmd/metrics/metadata.go
- cmd/metrics/metric.go
- cmd/metrics/metric_defs.go
Expanding uncore events to per-device events creates a very long list of event groups. In some cases the list is too large for perf to handle resulting in an "Argument list too long" error from perf. We have worked around this in the past by abbreviating event names to shorten the argument list.
Through investigating the problem above, we found that the individual uncore device event counters are not used independently. They are added together, and the sum is used. The original intent of uncore event expansion is unknown.
In this PR, we eliminate the expansion of uncore events. 
This pull request refactors the metrics event processing pipeline to simplify event handling and improve aggregation logic, especially for uncore events. It removes legacy abbreviation and group expansion logic, …
> refactor uncore event collection and handling

- internal/report/render_json.go
- internal/report/table_defs.go
This pull request improves the robustness of several hardware information table-generating functions in `internal/report/table_defs.go` by adding checks for empty or missing data. Now, if the underlying data for a table is absent, the functions will return an empty slice instead of attempting to build a table with invalid or incomplete data. This change helps prevent runtime errors and ensures more accurate reporting.
Data validation and error handling improvements:
* Added checks in `pcieSlotsTableValues`, `cstateTableValues`, `dimmTableValues`, `nicTableValues`, `networkIRQMappingTableValues`, `diskTableValues`, `gpuTableValues`, `gaudiTableValues`, and `cxlTableValues` to return an empty slice if the parsed data is empty, preventing attempts to build tables from missing or incomplete …
> report table data nil if no data

- cmd/root.go
- internal/report/table_helpers_cache.go
This pull request simplifies the logic for downloading the latest release tarball and improves error handling in the cache table helper. The most important changes are grouped below:
Release download logic simplification:
* The `updateApp` function in `cmd/root.go` now only attempts to download the unversioned tarball file (`perfspect.tgz`) instead of trying both versioned and unversioned variants, streamlining the update process.
* Improved error handling and logging for HTTP download failures, ensuring clearer messages when the download fails due to network issues or non-OK HTTP status codes.
Error handling improvements in cache table helpers:
* In `internal/report/table_helpers_cache.go`, the error handling for parsing "cores per socket" and "sockets" has been separated, with more …
> fix error handling

- cmd/metrics/event_frame.go
This pull request updates the event name normalization logic in the `parseEvents` function to avoid altering certain event names that are required to match metric formulas. Specifically, it ensures that event names starting with `power`, `cstate_core`, or `cstate_pkg` are preserved as-is.
Event name normalization improvements:
* Updated the logic in `parseEvents` to skip normalization for event names prefixed with `power`, `cstate_core`, or `cstate_pkg`, ensuring these event names remain unchanged for metric formula compatibility.
> fix regression where power and c6 residency not reported

- internal/report/table_defs.go
- internal/script/script_defs.go
Error reading SSTTF configuration results in garbled output:
This PR adds/improves error handling in the collection scripts and the table values function.
> improve SSTTF script error handling

- internal/report/table_helpers_turbostat.go
This pull request refactors the logic for parsing turbostat output to improve how summary (platform) and package rows are identified and extracted. The changes introduce helper functions for clearer row classification and enhance compatibility with different turbostat output formats.
**Row classification improvements:**
* Added the `isPlatformRow` helper function to accurately identify platform (summary) rows by checking that `Package`, `Die`, `Node`, `Core`, and `CPU` are all "-" or missing. This replaces previous inline logic and improves maintainability.
* Updated the `turbostatPlatformRows` function to use `isPlatformRow` for filtering, ensuring only platform rows are returned.
**Package row handling enhancements:**
* Added the `isPackageRow` helper function to identify package rows …
> fix get power stats from turbostat for telemetry

- Makefile
- internal/report/render_excel.go
- internal/report/render_html.go
- internal/report/table_defs.go
This pull request enhances the reporting features by adding support for field descriptions in both HTML and Excel reports. Field descriptions are now included in the data model, and are displayed as tooltips in HTML tables and as cell comments in Excel exports. These improvements make the reports more informative and user-friendly, especially for fields whose meaning may not be immediately obvious.
**Field Description Support**
* Added a `Description` member to the `Field` struct, allowing each field to include an optional description.
* Updated table construction functions (e.g., `cpuTableValues`, `systemSummaryTableValues`, `briefSummaryTableValues`, `frequencyBenchmarkTableValues`) to populate the new `Description` field for relevant fields, providing informative context for key …
> add description to report table field

- cmd/config/set.go
- internal/report/table_defs.go
- internal/report/table_helpers_cache.go
- internal/report/table_helpers_cache_test.go
- internal/script/script_defs.go
This pull request refactors how CPU cache sizes are parsed and reported, improving accuracy and consistency by leveraging the JSON output from the `lscpu -C -J` command. The changes affect both the cache reporting logic and the tables that display cache sizes, ensuring that values are correctly split between per-instance and total sizes, and that L1/L2 cache sizes are extracted more reliably.
**Cache reporting and parsing improvements:**
* Refactored cache size extraction to use the new `lscpuCacheScriptName` output, parsing its JSON to obtain L1d, L1i, L2, and L3 cache sizes, replacing previous regex-based extraction from plain text. [[1]](diffhunk://#diff-45d7f52943fc0d315b8375596890c4d6a6fc8bbcab61ff618a5aaf2cf18e9a6aR7-R105) [[2]](diffhunk://#diff-40020381fb8631bc46477e98732857d1990925 …
> cache sizes reported by type
